#Program to demonstrate exception

v1_str = input("Enter value for v1 = ");
v2_str = input("Enter value for v2 = ");

v1_int = int(v1_str)
v2_int = int(v2_str)

sum = v1_int + v2_int;
print("Sum of "+ v1_str + " and " + v2_str + " is :" + str(sum));

#Enter alphabet values for v1 or v2, the program with throw exception.
#Solution is in p4b.py
